workspace:
  base: /go
  path: src/github.com/thefury/gorrelation

pipeline:
  build:
    image: golang:${GO_VERSION}
    commands:
      - go get
      - go test

matrix:
  GO_VERSION:
    - latest
    - 1.9
    - 1.8
    - 1.7
    - 1.6

